#!/usr/bin/env python3 
from sys import argv
from os import system

outfile = argv[1] if len(argv) > 1 else 'targ_parser'


system(f"gcc targ_parser.c string_action.c -o {outfile}")
print(f"targ_parser compilé sous {outfile}")