#!/usr/bin/env python3 
from sys import argv
from os import system,getcwd
current_dir = "/".join(__file__.split("/")[0:-1])+"/"
outfile = argv[1] if len(argv) > 1 else 'targ_parser'


system(f"gcc {current_dir}targ_parser.c {current_dir}string_action.c -o {current_dir}{outfile}")
print(f"targ_parser compilé sous {current_dir}{outfile}")
